#ifndef __INCLUDE_CONFIG
#define __INCLUDE_CONFIG

#include <rte_kni.h>

#define DEFAULT_NB_MBUF 16384
#define DEFAULT_MTU 1500
#define DEFAULT_MBUF_DATAROOM 2048
#define DEFAULT_NB_RX_DESC 4096
#define DEFAULT_NB_TX_DESC 4096

#define BURST_SIZE 512

#define GPU_PAGE_SIZE (1U<<16)

#define DEFAULT_NB_QUEUES 1
#endif
